<a href="https://colab.research.google.com/github/nhatguku/colab/blob/master/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY EXERCISE**

**1. Import Numpy**

In [0]:
import numpy as np

**2. Manually create a matrix**

Create a 3-by-5 matrix and print it out to the screen

In [0]:
a = np.array([[1,2,3,4,10],[4,5,6,7,9],[4,6,5,3,4]]) 
a.shape = (3,5) 
print (a)

[[ 1  2  3  4 10]
 [ 4  5  6  7  9]
 [ 4  6  5  3  4]]


**3. Manually create a vector**

Create a vector which has 10 elements and print it out to the screen

In [0]:
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


**4. Automatically create matrix**



1.   Automatically create a 3-by-5 matrix which has interger values in the range of [0, 100]
2.   Automatically create a 5-by-7 matrix which has interger values in the range of [0, 100]
3.   Print out the above 2 matricces to the screen
4.   Implementy matrix multiplication of the above 2 matrices and print the result to the screen (let us call this result matrixx is C)




In [0]:
n = np.random.randint(1,100,(3,5))
print(n)

[[ 7 85 33 75 51]
 [29 23 39 55 39]
 [26 26 85 94 88]]


In [0]:
m = np.random.randint(0,100,(5,7))
print(m)

[[73 77 23  9 85 40 81]
 [89 68 25 38 59  5 66]
 [16 47 74 91 62 40 94]
 [75 36 14 87 70  6 50]
 [ 9 13 95 86 68 44 97]]


In [0]:
c = n.dot(m)
print(c)

[[14688 11233 10623 17207 16374  4719 17976]
 [ 9264  8117  8603 12823 12742  4881 14066]
 [13414 12293 17214 24703 21578  9006 25048]]


**5. Scalar multiplication**

Input a number fromm keyboard and multiply this number with the above matrix C and print the result to the screen

In [0]:
n = int(input("Random number from keyboard ="))

Random number from keyboard =4


In [0]:
d = n*c
print(d)

[[ 58752  44932  42492  68828  65496  18876  71904]
 [ 37056  32468  34412  51292  50968  19524  56264]
 [ 53656  49172  68856  98812  86312  36024 100192]]


**6. Automatically create vector**

Automattically create a vector at size of 7-by-1 which has values in the range of [-10, 30]. And multiply the C matrix with this vector. Print the result to the screen.

In [0]:
e = np.random.randint(-10,30,(7,1))
print(e)

[[13]
 [17]
 [ 1]
 [ 1]
 [15]
 [ 6]
 [11]]


In [0]:
q = c.dot(e)
print(q)

[[ 881395]
 [ 654989]
 [1078514]]


**7. Matrix slicing**



1.   Automatically create a matrix at size of 7-by-15
2.   Print out the first column of this matrix 
3.   Print out the third row of this matrix
4.   Print out the element at the second column and fourth row



In [0]:
e = np.random.randint(0,30,size=(7,15))
e

array([[ 1,  0, 15,  5, 23, 24, 29, 28, 17, 28, 11, 22, 17,  9,  0],
       [26, 22, 19, 19, 22, 13, 25, 11, 23,  1, 10,  0, 18, 29,  8],
       [ 9,  5, 16, 12, 16, 27,  6, 13,  6, 13,  7,  9,  5, 19, 14],
       [28, 11, 29, 10, 11,  4,  5,  5, 25, 22, 11, 27, 24, 21, 26],
       [25, 21, 21, 21,  3, 22,  2, 21, 13,  6, 15,  7, 28, 15, 21],
       [16, 10, 27,  5, 19, 23, 23, 24, 28, 11, 28, 27, 11,  1,  3],
       [13, 17, 25, 20, 29, 29, 25, 18, 21, 22, 12,  5, 27, 20, 27]])

In [0]:
e[:,[0]]

array([[ 1],
       [26],
       [ 9],
       [28],
       [25],
       [16],
       [13]])

In [0]:
e[2:3]

array([[ 9,  5, 16, 12, 16, 27,  6, 13,  6, 13,  7,  9,  5, 19, 14]])

In [0]:
e[1,3]

19

**8. Matrix transposition**

Perform the matrix transposition of the matrix in question 7 and print out to the screen.

In [0]:
e = np.random.randint(0,30,size=(7,15))
e.transpose()

array([[21, 29, 12, 28,  3, 28,  3],
       [27,  4,  2, 12,  9, 11, 18],
       [19, 22, 16,  5,  0, 19,  1],
       [27, 23, 14,  1, 14,  6,  5],
       [27, 28, 15, 20,  4, 25, 23],
       [19, 21,  6, 16, 10, 14,  0],
       [18, 24, 20, 25, 17, 19,  4],
       [ 8, 24,  3, 14, 10, 12, 16],
       [ 8, 19, 23, 25, 23, 18, 18],
       [14, 10, 25,  2,  4, 16, 20],
       [ 7,  9, 18, 12, 19, 21, 10],
       [23,  2,  9,  3, 23, 27, 26],
       [ 2, 14, 27, 11, 28, 13, 13],
       [22, 18, 25,  2,  4, 23, 18],
       [24,  8, 22, 16, 29,  6, 14]])

**9. Matrix addition**



1.   Automatically create 2 integer matrices whicch have values in the range of [-10, 30]
2.   Print them to the screen
3.   Perform matrix addition of the above 2 matrices and print the result to the screen. 



In [0]:
f = np.random.randint(-10,30,size=(3,5))
g = np.random.randint(-10,30,size=(3,5))
print(f)
print(g)

[[19 25 22 19 -6]
 [ 5 23  3  4 -6]
 [15 -7 28 27 22]]
[[ 25 -10  28   7   3]
 [ -9  19  -2  20   3]
 [ 27  15  12   9   2]]


In [0]:
np.add(f,g)

array([[44, 15, 50, 26, -3],
       [-4, 42,  1, 24, -3],
       [42,  8, 40, 36, 24]])